version: '3'
services:
  app:
    container_name: application
    ports: ["8080:8080"]
    build:
      context: application
      dockerfile: Dockerfile
    depends_on:
      - cassandra

  cassandra:
    image: cassandra
    container_name: cassandra
    restart: unless-stopped
    ports: ["9042:9042"]
    volumes:
      - "./cassandra/cassandra-init.sh:/cassandra-init.sh"
      - "./cassandra/init.cql:/init.cql"
      - "./cassandra/jcpenney_com-ecommerce_sample.csv:/jcpenney_com-ecommerce_sample.csv"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
